name: ci

on:
  pull_request:

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-app
      - run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-app
      - run: make format-check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-app
      - run: make typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-app
      - run: make test